# Generated by Django 4.0 on 2022-06-02 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_one', models.TextField(default=None)),
                ('question_two', models.TextField(default={})),
                ('question_three', models.TextField(default={})),
                ('question_four', models.TextField(default={})),
                ('question_six', models.TextField(default=[])),
                ('question_seven', models.TextField(default=None)),
                ('question_eight', models.TextField(default=None)),
                ('question_nine', models.TextField(default=None)),
                ('question_ten', models.TextField(default=None)),
                ('question_eleven', models.TextField(default=None)),
                ('question_twelve', models.TextField(default=None)),
                ('question_one_c', models.IntegerField(default=0)),
                ('question_two_c', models.IntegerField(default=0)),
                ('question_three_c', models.IntegerField(default=0)),
                ('question_four_c', models.IntegerField(default=0)),
                ('question_five_c', models.IntegerField(default=0)),
                ('question_six_c', models.IntegerField(default=0)),
                ('question_seven_c', models.IntegerField(default=0)),
                ('question_eight_c', models.IntegerField(default=0)),
                ('question_nine_c', models.IntegerField(default=0)),
                ('question_ten_c', models.IntegerField(default=0)),
                ('question_eleven_c', models.IntegerField(default=0)),
                ('question_twelve_c', models.IntegerField(default=0)),
                ('name', models.CharField(max_length=225)),
                ('verified', models.BooleanField(default=False)),
            ],
        ),
    ]
