# Generated by Django 4.0 on 2022-06-03 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_quiz_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='user',
            field=models.CharField(default=None, max_length=15),
        ),
    ]
