# Generated by Django 4.0 on 2022-06-04 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_quiz_question_one_alter_quiz_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
