# Generated by Django 4.0 on 2022-06-06 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_quiz_verified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='question_eleven',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='question_eleven_c',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='question_twelve',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='question_twelve_c',
        ),
        migrations.AddField(
            model_name='quiz',
            name='optA_question_eight',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='quiz',
            name='optA_question_five',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='quiz',
            name='optA_question_four',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='quiz',
            name='optA_question_nine',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='quiz',
            name='optA_question_one',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='quiz',
            name='optA_question_seven',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='quiz',
            name='optA_question_six',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='quiz',
            name='optA_question_ten',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='quiz',
            name='optA_question_three',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='quiz',
            name='optA_question_two',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='quiz',
            name='optB_question_eight',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='quiz',
            name='optB_question_five',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='quiz',
            name='optB_question_four',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='quiz',
            name='optB_question_nine',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='quiz',
            name='optB_question_one',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='quiz',
            name='optB_question_seven',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='quiz',
            name='optB_question_six',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='quiz',
            name='optB_question_ten',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='quiz',
            name='optB_question_three',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='quiz',
            name='optB_question_two',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='quiz',
            name='optC_question_eight',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='quiz',
            name='optC_question_five',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='quiz',
            name='optC_question_four',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='quiz',
            name='optC_question_nine',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='quiz',
            name='optC_question_one',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='quiz',
            name='optC_question_seven',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='quiz',
            name='optC_question_six',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='quiz',
            name='optC_question_ten',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='quiz',
            name='optC_question_three',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='quiz',
            name='optC_question_two',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='quiz',
            name='question_five',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='question_one',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='user',
            field=models.CharField(blank=True, default=None, max_length=15, null=True),
        ),
    ]
