# Generated by Django 4.0 on 2022-06-06 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_remove_quiz_question_eleven_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAnswer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user', models.CharField(blank=True, default=None, max_length=15, null=True)),
                ('name', models.CharField(blank=True, max_length=225, null=True)),
                ('verified', models.BooleanField(blank=True, default=False)),
                ('answer_one', models.CharField(default=None, max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='name',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='user',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='verified',
        ),
        migrations.AlterField(
            model_name='quiz',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
