# Generated by Django 4.0 on 2022-06-06 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_useranswer_remove_quiz_name_remove_quiz_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='useranswer',
            name='answer_eight',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='useranswer',
            name='answer_five',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='useranswer',
            name='answer_four',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='useranswer',
            name='answer_nine',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='useranswer',
            name='answer_seven',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='useranswer',
            name='answer_six',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='useranswer',
            name='answer_ten',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='useranswer',
            name='answer_three',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='useranswer',
            name='answer_two',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
