# Generated by Django 4.0 on 2022-06-06 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_useranswer_answer_eight_useranswer_answer_five_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useranswer',
            name='answer_eight',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='useranswer',
            name='answer_five',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='useranswer',
            name='answer_four',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='useranswer',
            name='answer_nine',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='useranswer',
            name='answer_one',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='useranswer',
            name='answer_seven',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='useranswer',
            name='answer_six',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='useranswer',
            name='answer_ten',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='useranswer',
            name='answer_three',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='useranswer',
            name='answer_two',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
    ]
