# Generated by Django 4.0 on 2022-06-07 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_useranswer_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='useranswer',
            name='total',
            field=models.IntegerField(default=0),
        ),
    ]
