# Generated by Django 4.0 on 2022-06-08 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_useranswer_answer_eightc_useranswer_answer_fivec_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='useranswer',
            name='answerEight_status',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='useranswer',
            name='answerFive_status',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='useranswer',
            name='answerFour_status',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='useranswer',
            name='answerNine_status',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='useranswer',
            name='answerOne_status',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='useranswer',
            name='answerSeven_status',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='useranswer',
            name='answerSix_status',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='useranswer',
            name='answerTen_status',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='useranswer',
            name='answerThree_status',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='useranswer',
            name='answertwo_status',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
