# Generated by Django 4.0.5 on 2022-07-06 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_useranswer_answereight_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='useranswer',
            name='Bank_name',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='useranswer',
            name='winneraccount',
            field=models.IntegerField(blank=True, default=None, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='useranswer',
            name='winnername',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
    ]
