# Generated by Django 4.0.5 on 2022-07-06 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_useranswer_bank_name_useranswer_winneraccount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useranswer',
            name='winneraccount',
            field=models.CharField(blank=True, default=None, max_length=10, null=True),
        ),
    ]
