# Generated by Django 4.0.5 on 2022-07-06 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_alter_useranswer_winnernumber'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useranswer',
            name='winnernumber',
        ),
    ]
