# Generated by Django 4.0.5 on 2022-07-06 22:26

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_remove_useranswer_winnernumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='useranswer',
            name='winnernumber',
            field=phonenumber_field.modelfields.PhoneNumberField(default=None, max_length=128, region=None),
            preserve_default=False,
        ),
    ]
