# Generated by Django 4.0.5 on 2022-07-06 22:32

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_useranswer_winnernumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useranswer',
            name='user',
            field=phonenumber_field.modelfields.PhoneNumberField(default=None, max_length=128, region=None),
        ),
    ]
