# Generated by Django 4.0.5 on 2022-07-06 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_alter_useranswer_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useranswer',
            name='user',
            field=models.CharField(blank=True, default=None, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='useranswer',
            name='winnernumber',
            field=models.CharField(blank=True, default=None, max_length=11, null=True),
        ),
    ]
