# Generated by Django 4.0.5 on 2022-07-07 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_quiz_fastwinner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='fastwinner',
            field=models.CharField(blank=True, default=None, max_length=50),
        ),
    ]
