# Generated by Django 4.0.5 on 2022-07-07 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_alter_quiz_fastwinner'),
    ]

    operations = [
        migrations.AddField(
            model_name='useranswer',
            name='fastwinner',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
